CREATE TABLE `typecho_access` (
  `id`                int(10) unsigned NOT NULL auto_increment COMMENT '序号',
  `ua`                varchar(255)     default ''              COMMENT 'UA',
  `browser_id`        varchar(32)      default ''              COMMENT '浏览器名称',
  `browser_version`   varchar(32)      default ''              COMMENT '浏览器版本',
  `os_id`             varchar(32)      default ''              COMMENT '系统名称',
  `os_version`        varchar(32)      default ''              COMMENT '系统版本',
  `url`               varchar(255)     default ''              COMMENT '统一资源定位符',
  `path`              varchar(255)     default ''              COMMENT '路径',
  `query_string`      varchar(255)     default ''              COMMENT '请求参数',
  `ip`                int(32) unsigned default '0'             COMMENT 'IP',
  `entrypoint`        varchar(255)     default ''              COMMENT '入口点',
  `entrypoint_domain` varchar(100)     default ''              COMMENT '入口域名',
  `referer`           varchar(255)     default ''              COMMENT 'Referer',
  `referer_domain`    varchar(100)     default ''              COMMENT '来源域名',
  `time`              int(32) unsigned default '0'             COMMENT '时间戳',
  `content_id`        int(10) unsigned default NULL            COMMENT '内容',
  `meta_id`           int(10) unsigned default NULL            COMMENT '索引序号',
  `robot`             tinyint(1)       default '0'             COMMENT '是否爬虫',
  `robot_id`          varchar(32)      default ''              COMMENT '爬虫名称',
  `robot_version`     varchar(32)      default ''              COMMENT '爬虫版本',
  PRIMARY KEY (`id`),
  KEY `idx_time`              (`time`             ),
  KEY `idx_path`              (`path`             ),
  KEY `idx_ip_ua`             (`ip`,`ua`          ),
  KEY `idx_robot`             (`robot`, `time`    ),
  KEY `idx_os_id`             (`os_id`            ),
  KEY `idx_robot_id`          (`robot_id`         ),
  KEY `idx_browser_id`        (`browser_id`       ),
  KEY `idx_content_id`        (`content_id`       ),
  KEY `idx_meta_id`           (`meta_id`          ),
  KEY `idx_entrypoint`        (`entrypoint`       ),
  KEY `idx_entrypoint_domain` (`entrypoint_domain`),
  KEY `idx_referer`           (`referer`          ),
  KEY `idx_referer_domain`    (`referer_domain`   )
) ENGINE=InnoDB DEFAULT CHARSET=%charset%;